apiVersion: apps/v1
kind: Deployment
metadata:
    name: every-nownthen
    namespace: vetify
    labels:
        app: every-nownthen
spec:
    replicas: 1
    strategy:
        type: Recreate
    selector:
        matchLabels:
            app: every-nownthen
    template:
        metadata:
            labels:
                app: every-nownthen
        spec:
            containers:
                - name: every-nownthen
                  image: <IMAGE>
                  imagePullPolicy: Always

                  envFrom:
                      - secretRef:
                            name: every-nownthen-env-secret

                  env:
                      - name: TZ
                        value: "Africa/Luanda"

                  volumeMounts:
                      - name: service-account-key
                        mountPath: /etc/service_account.json
                        subPath: service_account.json
                        readOnly: true

                  resources:
                      requests:
                          memory: "256Mi"
                          cpu: "100m"
                      limits:
                          memory: "512Mi"
                          cpu: "500m"

            volumes:
                - name: service-account-key
                  secret:
                      secretName: every-nownthen-service-account-secret
                      items:
                          - key: service_account.json
                            path: service_account.json
